config/routes.rb
Rails.application.routes.draw do
  resources :happywords

  root 'happywords#index'

end

app/models/happyword.rb
class Happyword < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/happywords_controller.rb
class HappywordsController < ApplicationController
  before_action :set_happyword, only: [:show, :edit, :update, :destroy]
  before_action :set_jokes
  before_action :set_adages

  # GET /happywords
  # GET /happywords.json
  def index
    @happyword = Happyword.all
    @max_joke_id = @jokes.count
    @max_adage_id = @adages.count + @jokes.count
    @rand_joke = @jokes.find(rand(1..@max_joke_id))
    @rand_adage = @adages.find(rand((@max_joke_id + 1)..@max_adage_id))
  end

  # GET /happywords/1
  # GET /happywords/1.json
  def show
  end

  # GET /happywords/new
  def new
    @happyword = Happyword.new
  end

  # GET /happywords/1/edit
  def edit
  end

  # POST /happywords
  # POST /happywords.jsonwith 
  def create
    @happyword = Happyword.new(happyword_params)

    respond_to do |format|
      if @happyword.save
        format.html { redirect_to @happyword, notice: 'Happyword was successfully created.' }
        format.json { render :show, status: :created, location: @happyword }
      else
        format.html { render :new }
        format.json { render json: @happyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /happywords/1
  # PATCH/PUT /happywords/1.json
  def update
    respond_to do |format|
      if @happyword.update(happyword_params)
        format.html { redirect_to @happyword, notice: 'Happyword was successfully updated.' }
        format.json { render :show, status: :ok, location: @happyword }
      else
        format.html { render :edit }
        format.json { render json: @happyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /happywords/1
  # DELETE /happywords/1.json
  def destroy
    @happyword.destroy
    respond_to do |format|
      format.html { redirect_to happywords_url, notice: 'Happyword was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_happyword
      @happyword = Happyword.find(params[:id])
    end

    def set_jokes
      @jokes = Happyword.where(genre:'joke')
    end

    def set_adages
      @adages = Happyword.where(genre:'adage')
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def happyword_params
      params.require(:happyword).permit(:genre, :phrase)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/happywords_helper.rb
module HappywordsHelper
end

app/views/happywords/_form.html.erb
<%= form_for(@happyword) do |f| %>
  <% if @happyword.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@happyword.errors.count, "error") %> prohibited this happyword from being saved:</h2>

      <ul>
      <% @happyword.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :genre %><br>
    <%= f.text_field :genre %>
  </div>
  <div class="field">
    <%= f.label :phrase %><br>
    <%= f.text_area :phrase %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/happywords/edit.html.erb
<h1>Editing Happyword</h1>

<%= render 'form' %>

<%= link_to 'Show', @happyword %> |
<%= link_to 'Back', happywords_path %>

app/views/happywords/index.html.erb
<html>
  <p id="ajax-text"></p>

    <%= button_to "Get a Joke", @rand_joke, remote: true, method: :get %><%= button_to "Get an Adage", @rand_adage, remote: true, method: :get %>

    <script src="//code.jquery.com/jquery-1.11.3.min.js"></script>
    <script>
    
      $(function () {
        function randomIntFromInterval(min,max) { return Math.floor(Math.random()*(max-min+1)+min); }
        $("input").click(function (e){
          var valueClicked = e.target.value;
          if (valueClicked === "Get a Joke") {
            var url = "./happywords/" + randomIntFromInterval(1, 3);
          } else{
            var url = "./happywords/" + randomIntFromInterval(4, 6);
          };

          $.get(url, function (happyword) {
            var start_pos = happyword.indexOf('<body>') + 6;
            var end_pos = happyword.indexOf('</body>',start_pos);
            var text_to_get = happyword.substring(start_pos,end_pos);
            $("#ajax-text").text(text_to_get);
          });
        });
      });
    </script>

</html>

app/views/happywords/new.html.erb
<h1>New Happyword</h1>

<%= render 'form' %>

<%= link_to 'Back', happywords_path %>

app/views/happywords/show.html.erb
<%= @happyword.phrase %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HappyApp4</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>